### ISSUE TITLE
Using MozFest/MoFo Credentials for Deploying the App

### ISSUE THREAD

**Issue by liberaliscomputing** [liberaliscomputing/network-mapping-js#6]
This app targets to render the evolution of networks among participants in real-time during MozFest, using the Twitter Streaming API.
For prototyping this project, I have been using my personal credentials for Twitter API OAuth.
Since this project is getting close to a beta stage, I might have to look at whether MozFest/MoFo's Twitter account can be used to obtain API keys for this tool.
@simonwex @pomax

**Comment by alanmoo** [comment]
@cadecairos may be able to help. @liberaliscomputing Do you have the project configured to read keys from a .env variable?

**Comment by liberaliscomputing** [comment]
Thanks, @alanmoo ! I will talk about this issue at Today's engineering call. And yes, the project is using a python package called `dotenv` to load credentials in .env!

**Comment by cadecairos** [comment]
I don't have access to any of MoFo's Twitter accounts, so I'll have to find the right person and get the credentials from them. 

@simonwex do you know who might have access to Twitter accounts? I'll get them to put the creds in the vault.
